apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pl6qksymv-python 
  janus-idp.io/tekton: pl6qksymv-python
  backstage.io/kubernetes-id: pl6qksymv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pl6qksymv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml